// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBXvlXKBV0CDrinG8dGGFk0n--HeYlepg',
    appId: '1:877108895509:web:0680644f9ba9570e17d31c',
    messagingSenderId: '877108895509',
    projectId: 'learnmath-624b0',
    authDomain: 'learnmath-624b0.firebaseapp.com',
    databaseURL: 'https://learnmath-624b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnmath-624b0.firebasestorage.app',
    measurementId: 'G-4HTYYRPKNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hkzJgWtIbW--6jNbGE_hdTBbdEpqvDs',
    appId: '1:877108895509:android:a8db4958f297e0a117d31c',
    messagingSenderId: '877108895509',
    projectId: 'learnmath-624b0',
    databaseURL: 'https://learnmath-624b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnmath-624b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkX7g-7OmxCWVUjuJPeP8kaXrkN3gHPxI',
    appId: '1:877108895509:ios:d8915ea4a718a6c117d31c',
    messagingSenderId: '877108895509',
    projectId: 'learnmath-624b0',
    databaseURL: 'https://learnmath-624b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnmath-624b0.firebasestorage.app',
    iosBundleId: 'com.example.learnmathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkX7g-7OmxCWVUjuJPeP8kaXrkN3gHPxI',
    appId: '1:877108895509:ios:d8915ea4a718a6c117d31c',
    messagingSenderId: '877108895509',
    projectId: 'learnmath-624b0',
    databaseURL: 'https://learnmath-624b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnmath-624b0.firebasestorage.app',
    iosBundleId: 'com.example.learnmathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBXvlXKBV0CDrinG8dGGFk0n--HeYlepg',
    appId: '1:877108895509:web:d8d50c8b97719d8717d31c',
    messagingSenderId: '877108895509',
    projectId: 'learnmath-624b0',
    authDomain: 'learnmath-624b0.firebaseapp.com',
    databaseURL: 'https://learnmath-624b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnmath-624b0.firebasestorage.app',
    measurementId: 'G-6W2SDGYDMD',
  );

}